image: node

stages:
  - lint

eslint:
  stage: lint
  script:
    - |
      npm install eslint \
      eslint-plugin-flowtype \
      eslint-plugin-import \
      eslint-plugin-jsx-a11y
    - node_modules/eslint/bin/eslint.js src