image: node

stages:
  - lint
  - build

eslint:
  stage: lint
  script:
    - |
      npm install eslint \
      eslint-plugin-flowtype \
      eslint-plugin-import \
      eslint-plugin-jsx-a11y
    - node_modules/eslint/bin/eslint.js app.js


build-image:
  stage: build
  tags: 
    - deploy
  script:
    - docker build -t ws-transaksi .
    - docker run --name ws -d ws-transaksi 
