image: node

stages:
  - lint
  - build

eslint:
  stage: lint
  script:
    - |
      npm install eslint \
      eslint-plugin-flowtype \
      eslint-plugin-import \
      eslint-plugin-jsx-a11y
    - node_modules/eslint/bin/eslint.js app.js


build-image:
  stage: build
  only: 
    - master
  tags: 
    - deploy
  script:
    - docker stop ws || true && docker rm ws || true
    - docker build -o ./ -t ws-transaksi .
    - docker run --name ws -p 3000:3000 -d ws-transaksi 
